'use client';

import { useSoarStore } from '@/lib/soar-store';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import {
  ArrowLeft, Download, Copy, CheckCircle, AlertTriangle, XCircle, Info,
  Settings, Pencil, ClipboardCopy, ShieldCheck, FileText, Printer,
} from 'lucide-react';
import { useState, useMemo } from 'react';
import {
  generateFortiSOARExportPackage,
  buildDefaultDeploymentProfile,
  generateFortiSOARWorkflowCollection,
  validateConfigValue,
  type ConfigValidationStatus,
  type FortiSOARExportPackage,
} from '@/lib/fortisoar-workflow-generator';
import {
  SOAR_QA_MATRIX,
  runQAReportRow,
  type QAReportRow,
} from '@/lib/soar-qa-matrix';
import { getPlatformById, type SoarPlatformId } from '@/lib/soar-platforms';
import { PlatformExportBadge } from './compatibility-badge';
import ConnectorConfigModal from './connector-config-modal';
import { getPlatformAdapter } from '@/lib/adapters/adapter-registry';
import { buildNormalizedPlaybook } from '@/lib/normalized/build-normalized-playbook';
import {
  generateCustomerDocument,
  exportToMarkdown as exportCustomerDocMarkdown,
  exportToHTML as exportCustomerDocHTML,
} from '@/lib/documentation/customer-documentation-generator';
import { DocumentationPreview } from '@/components/documentation-preview';
import { ExportReadinessPanel } from '@/components/export-readiness-panel';
import { evaluateExportReadiness } from '@/lib/evidence/export-readiness-engine';
import { ThreatCoveragePanel } from '@/components/threat-knowledge/threat-coverage-panel';
import { analyzeThreatCoverage, exportThreatCoverageMarkdown } from '@/lib/threat-knowledge/threat-coverage-analyzer';
import { IntelligenceReviewPanel } from '@/components/intelligence/intelligence-review-panel';
import { analyzePlaybookIntelligence } from '@/lib/intelligence/recommendation-engine';
import { exportIntelligenceReviewMarkdown } from '@/lib/intelligence/intelligence-report-export';

// ── Per-platform export card metadata ───────────────────────────────────────

interface PlatformExportMeta {
  title: string;
  subtitle: string;
  description: string;
  filenameSuffix: string;
  ext: 'json' | 'md';
}

const PLATFORM_EXPORT_META: Record<SoarPlatformId, PlatformExportMeta> = {
  fortisoar: {
    title: 'FortiSOAR Workflow JSON',
    subtitle: 'Direct FortiSOAR import',
    description: 'Direct FortiSOAR import file. Contains the workflow_collections structure required by FortiSOAR. Replace template placeholders with actual connector UUIDs.',
    filenameSuffix: 'fortisoar_workflow',
    ext: 'json',
  },
  cortex_xsoar: {
    title: 'Cortex XSOAR Content Pack Blueprint',
    subtitle: 'Blueprint — verify in tenant',
    description: 'Blueprint/draft for Cortex XSOAR. Verify integration instances, command names, and incident field mappings in your tenant before use.',
    filenameSuffix: 'cortex_xsoar_content_pack_blueprint',
    ext: 'json',
  },
  splunk_soar: {
    title: 'Splunk SOAR Blueprint',
    subtitle: 'Blueprint — verify app assets',
    description: 'Blueprint for Splunk SOAR playbook/action blocks. Verify app assets and action names in your tenant. Replace {{SPLUNK_*_ASSET}} placeholders.',
    filenameSuffix: 'splunk_soar_blueprint',
    ext: 'json',
  },
  sentinel_logic_apps: {
    title: 'Sentinel Logic App ARM Blueprint',
    subtitle: 'ARM/Logic App — deploy to Azure',
    description: 'ARM/Logic App blueprint with API connection placeholders. Deploy ARM template, configure API connections, then enable the automation rule.',
    filenameSuffix: 'sentinel_logic_app_arm',
    ext: 'json',
  },
  qradar_soar: {
    title: 'QRadar SOAR Blueprint',
    subtitle: 'Blueprint only — .resz not generated',
    description: 'Blueprint only. Direct .resz export is not generated by SOARForge. Use as reference architecture for manual QRadar SOAR workflow creation.',
    filenameSuffix: 'qradar_soar_blueprint',
    ext: 'json',
  },
  servicenow_secops: {
    title: 'ServiceNow SecOps Flow Blueprint',
    subtitle: 'Blueprint only — XML not generated',
    description: 'Blueprint only. XML Update Set export is not generated. Use as reference for manual Flow Designer creation in your ServiceNow tenant.',
    filenameSuffix: 'servicenow_secops_flow_blueprint',
    ext: 'json',
  },
  tines: {
    title: 'Tines Story JSON',
    subtitle: 'Tines story blueprint',
    description: 'Tines story blueprint with agents and links. Verify agent types, credentials, and action parameters in your Tines tenant after import.',
    filenameSuffix: 'tines_story_blueprint',
    ext: 'json',
  },
  shuffle: {
    title: 'Shuffle Workflow JSON',
    subtitle: 'Shuffle workflow blueprint',
    description: 'Shuffle workflow blueprint with nodes and edges. Verify app/action references and authentication credentials in your Shuffle environment.',
    filenameSuffix: 'shuffle_workflow_blueprint',
    ext: 'json',
  },
  generic_soar: {
    title: 'Normalized SOAR Blueprint',
    subtitle: 'Vendor-neutral blueprint',
    description: 'Vendor-neutral normalized SOAR/CACAO-style blueprint. Use for documentation, comparison, or as input to custom adapters for other platforms.',
    filenameSuffix: 'normalized_soar_blueprint',
    ext: 'json',
  },
};

// ── Fixed export types (always present) ─────────────────────────────────────

type FixedExportType = 'project_state' | 'platform_export' | 'normalized_blueprint' | 'full_package' | 'documentation' | 'connector_checklist' | 'customer_documentation' | 'threat_coverage_report' | 'intelligence_review' | 'customer_delivery_pack';

interface ExportCardMeta {
  type: FixedExportType;
  title: string;
  subtitle: string;
  description: string;
}

function buildExportCards(platform: SoarPlatformId): ExportCardMeta[] {
  const pMeta = PLATFORM_EXPORT_META[platform] ?? PLATFORM_EXPORT_META.generic_soar;
  return [
    {
      type: 'project_state',
      title: 'Project State JSON',
      subtitle: 'SOARForge only',
      description: 'Internal state file for reloading and editing this playbook in SOARForge. Not a SOAR platform import file.',
    },
    {
      type: 'normalized_blueprint',
      title: 'Normalized SOAR Blueprint',
      subtitle: 'Vendor-neutral JSON',
      description: 'Platform-agnostic normalized blueprint. Useful for comparison across platforms or feeding custom adapters.',
    },
    {
      type: 'threat_coverage_report',
      title: 'Threat Coverage Report',
      subtitle: 'MITRE-aware readiness',
      description: 'Customer-friendly threat coverage summary with technique coverage, defensive countermeasures, detection references, and recommended enhancements.',
    },
    {
      type: 'intelligence_review',
      title: 'SOARForge Intelligence Review',
      subtitle: 'Advisor analysis',
      description: 'Hybrid intelligence review with best-practice analysis, explain-why recommendations, safety guardrails, and safe auto-hardening preview.',
    },
    {
      type: 'customer_delivery_pack',
      title: 'Customer Delivery Pack',
      subtitle: 'Executive + analyst handover',
      description: 'Customer-ready delivery manifest including workflow export, implementation guide, threat coverage, intelligence review, validation checklist, and test plan.',
    },
    {
      type: 'platform_export',
      title: pMeta.title,
      subtitle: pMeta.subtitle,
      description: pMeta.description,
    },
    {
      type: 'full_package',
      title: 'Full Deployment Package',
      subtitle: 'Complete delivery package',
      description: 'Complete delivery package: platform export, normalized blueprint, deployment profile, connector mapping, readiness checks, and documentation.',
    },
    {
      type: 'documentation',
      title: 'Documentation Markdown',
      subtitle: 'Implementation guide',
      description: 'Platform-aware implementation guide, UAT plan, rollback plan, and connector matrix for the selected target platform.',
    },
    {
      type: 'connector_checklist',
      title: 'Connector/Action Checklist',
      subtitle: 'Tenant verification list',
      description: 'Per-connector and per-action verification checklist for the selected target platform.',
    },
    {
      type: 'customer_documentation',
      title: 'Customer Documentation',
      subtitle: 'Professional PDF-ready guide',
      description: 'Professional customer-facing implementation guide with Beta branding, architecture diagrams, scoring details, and deployment checklist.',
    },
  ];
}

// ── Status meta ──────────────────────────────────────────────────────────────

const STATUS_META: Record<string, { bg: string; border: string; text: string; icon: typeof CheckCircle }> = {
  draft:                  { bg: 'bg-gray-900/50',    border: 'border-gray-700/30',    text: 'text-gray-400',    icon: Info },
  ready_for_configuration:{ bg: 'bg-yellow-900/20',  border: 'border-yellow-700/30',  text: 'text-yellow-400',  icon: AlertTriangle },
  ready_for_uat:          { bg: 'bg-blue-900/20',    border: 'border-blue-700/30',    text: 'text-blue-400',    icon: Info },
  ready_for_import:       { bg: 'bg-green-900/20',   border: 'border-green-700/30',   text: 'text-green-400',   icon: CheckCircle },
  production_ready:       { bg: 'bg-emerald-900/20', border: 'border-emerald-700/30', text: 'text-emerald-400', icon: CheckCircle },
};

const CONNECTOR_STATUS_COLORS: Record<ConfigValidationStatus, string> = {
  valid:       'text-green-400 bg-green-900/20 border-green-800/30',
  placeholder: 'text-blue-400 bg-blue-900/20 border-blue-800/30',
  fake:        'text-red-400 bg-red-900/20 border-red-800/30',
  invalid:     'text-yellow-400 bg-yellow-900/20 border-yellow-800/30',
  empty:       'text-gray-400 bg-gray-800/20 border-gray-700/30',
};

const CONNECTOR_STATUS_LABEL: Record<ConfigValidationStatus, string> = {
  valid: 'Valid UUID',
  placeholder: 'Placeholder',
  fake: 'Fake Value',
  invalid: 'Invalid',
  empty: 'Not Set',
};

// ── Main component ────────────────────────────────────────────────────────────

export default function ExportCenter() {
  const {
    playbook,
    deploymentProfile,
    setIsExporting,
    setCurrentStep,
    openConnectorModal,
    targetPlatform,
  } = useSoarStore();

  const [copied, setCopied] = useState<FixedExportType | null>(null);
  const [copiedConnector, setCopiedConnector] = useState<string | null>(null);
  const [selectedExport, setSelectedExport] = useState<FixedExportType>('platform_export');

  // ── Build all exports ──────────────────────────────────────────────────────
  const exports = useMemo(() => {
    const profile = deploymentProfile || buildDefaultDeploymentProfile(playbook);
    const slug = playbook.name.toLowerCase().replace(/\s+/g, '-') || 'soarforge';

    // FortiSOAR path — use existing generator
    const fortiPkg = generateFortiSOARExportPackage(playbook, profile);

    // Normalized blueprint — always generated
    const normalized = buildNormalizedPlaybook(playbook, targetPlatform);

    // Threat coverage — customer-friendly MITRE/D3FEND advisory layer
    const threatCoverage = analyzeThreatCoverage(playbook, normalized, targetPlatform);
    const threatCoverageMarkdown = exportThreatCoverageMarkdown(threatCoverage);

    const adapterForReadiness = getPlatformAdapter(targetPlatform);
    const adapterReadiness = adapterForReadiness.validateReadiness(normalized, {
      ...(profile ?? {}),
      _playbookState: playbook,
    });
    const intelligenceExportReadiness = evaluateExportReadiness(normalized, targetPlatform, adapterReadiness);
    const intelligenceReview = analyzePlaybookIntelligence({
      playbook,
      normalized,
      targetPlatform,
      threatCoverage,
      exportReadiness: intelligenceExportReadiness,
    });
    const intelligenceReviewMarkdown = exportIntelligenceReviewMarkdown(intelligenceReview);
    const customerDeliveryPackMarkdown = [
      `# Customer Delivery Pack — ${playbook.name}`,
      '',
      `**Target Platform:** ${targetPlatform}`,
      `**Generated:** ${new Date().toISOString()}`,
      `**Knowledge Base Version:** ${intelligenceReview.knowledgeBaseVersion?.threatKnowledge ?? 'local'} / Platform ${intelligenceReview.knowledgeBaseVersion?.platformCompatibility ?? '1.0'} / Rules ${intelligenceReview.knowledgeBaseVersion?.recommendationRules ?? '1.0'}`,
      '',
      '## Executive Summary',
      intelligenceReview.executiveSummary || intelligenceReview.summary,
      '',
      '## What SOARForge Analyzed',
      '| Area | What Was Analyzed | Customer Value |',
      '|---|---|---|',
      ...(intelligenceReview.whatSoarForgeAnalyzed ?? []).map((item) => `| ${item.area} | ${item.analyzed} | ${item.customerValue} |`),
      '',
      '## Knowledge Update Status',
      intelligenceReview.knowledgeUpdateInsight?.summary ?? 'This package uses the local reviewed knowledge base. Knowledge updates require review and approval before changing local datasets.',
      '',
      '| Knowledge Source | Status | Version | Purpose |',
      '|---|---|---|---|',
      ...(intelligenceReview.knowledgeSources ?? []).map((item) => `| ${item.source} | ${item.status.replace(/_/g, ' ')} | ${item.version} | ${item.purpose} |`),
      '',
      '## Live Knowledge Update Readiness',
      `Status: ${intelligenceReview.liveKnowledgeUpdateReview?.status?.replace(/_/g, ' ') ?? 'not checked'}`,
      `Mode: ${intelligenceReview.liveKnowledgeUpdateReview?.mode?.replace(/_/g, ' ') ?? 'local only'}`,
      `Staged diff items: ${intelligenceReview.liveKnowledgeUpdateReview?.diffItems.length ?? 0}`,
      `Affected templates: ${intelligenceReview.liveKnowledgeUpdateReview?.templateImpacts.length ?? 0}`,
      `Admin approval required: ${intelligenceReview.liveKnowledgeUpdateReview?.adminApprovalRequired ? 'Yes' : 'No'}`,
      '',
      '| Affected Template | Impact | Recommended Action |',
      '|---|---|---|',
      ...((intelligenceReview.liveKnowledgeUpdateReview?.templateImpacts ?? []).map((impact) => `| ${impact.templateName} | ${impact.impact.replace(/_/g, ' ')} | ${impact.recommendedAction} |`)),
      '',
      '## Included Artifacts',
      '| Artifact | Status | Purpose |',
      '|---|---|---|',
      ...(intelligenceReview.customerDeliveryPackManifest ?? []).map((item) => `| ${item.file} | ${item.included ? 'Included' : 'Pending'} | ${item.purpose} |`),
      '',
      '## Primary Validation Items',
      '| Validation Item | Owner | Status | Evidence Required |',
      '|---|---|---|---|',
      ...(intelligenceReview.tenantValidationChecklist ?? []).slice(0, 12).map((item) => `| ${item.label} | ${item.owner} | ${item.status.replace(/_/g, ' ')} | ${item.validationEvidence} |`),
      '',
      '## Suggested UAT Tests',
      '| Scenario | Expected Path | Approval | Rollback |',
      '|---|---|---|---|',
      ...(intelligenceReview.testCaseRecommendations ?? []).map((test) => `| ${test.scenario} | ${test.expectedPath} | ${test.approvalExpected ? 'Yes' : 'No'} | ${test.rollbackExpected ? 'Yes' : 'No'} |`),
      '',
      '## Key Recommendations',
      ...intelligenceReview.recommendations.slice(0, 6).map((rec) => `- **${rec.title}:** ${rec.customerFacingText}`),
      '',
      '## Readiness Impact Note',
      'Validation status directly affects readiness confidence. When connector checks, non-production UAT paths, and rollback evidence are marked as passed, SOARForge can raise tenant-specific readiness confidence without promoting those results to other customers.',
      '',
      '## Runtime Notice',
      'This delivery pack separates design maturity from runtime certification. Production activation requires tenant connector validation, permission checks, and non-production execution evidence.',
    ].join('\n');

    // Platform-specific export via adapter
    let platformContent: unknown;
    let platformFileName: string;
    let adapterDocumentation: string;
    let connectorChecklist: string;

    const pMeta = PLATFORM_EXPORT_META[targetPlatform] ?? PLATFORM_EXPORT_META.generic_soar;

    if (targetPlatform === 'fortisoar') {
      platformContent = fortiPkg.workflowCollection;
      platformFileName = `${slug}_${pMeta.filenameSuffix}.json`;
      adapterDocumentation = buildFortiSOARDocumentation(fortiPkg);
      connectorChecklist = buildFortiSOARConnectorChecklist(profile);
    } else {
      const adapter = getPlatformAdapter(targetPlatform);
      const result = adapter.generateExport(normalized, {});
      platformContent = result.content;
      platformFileName = `${slug}_${pMeta.filenameSuffix}.json`;
      adapterDocumentation = adapter.generateDocumentation(normalized);
      connectorChecklist = adapter.generateConnectorChecklist(normalized);
    }

    // Generate customer documentation
    const customerDoc = generateCustomerDocument(playbook, normalized, targetPlatform);
    const customerDocMarkdown = exportCustomerDocMarkdown(customerDoc);
    const customerDocHTML = exportCustomerDocHTML(customerDoc, true);

    // Full deployment package — platform-aware, never leaks FortiSOAR data to non-FortiSOAR
    const platformInfo = getPlatformById(targetPlatform);
    const fullPackage = {
      metadata: {
        selectedPlatform: targetPlatform,
        platformName: platformInfo?.name ?? targetPlatform,
        exportType: targetPlatform === 'fortisoar' ? 'direct_import' : 'blueprint',
        directImportSupported: platformInfo?.directImportSupported ?? false,
        blueprintOnly: platformInfo?.blueprintOnly ?? true,
        requiresTenantVerification: platformInfo?.requiresTenantVerification ?? true,
        generatedAt: new Date().toISOString(),
        playbookName: playbook.name,
        playbookVersion: '1.0.0',
      },
      normalizedBlueprint: normalized,
      threatCoverage,
      intelligenceReview,
      customerDeliveryPack: customerDeliveryPackMarkdown,
      platformSpecificExport: platformContent,
      deploymentProfile: targetPlatform === 'fortisoar' ? profile : null,
      connectorMapping: connectorChecklist,
      readinessChecks: fortiPkg.readinessChecks,
      documentation: adapterDocumentation,
      tenantVerificationChecklist: pMeta.description,
    };

    return {
      project_state: JSON.stringify(playbook, null, 2),
      normalized_blueprint: JSON.stringify(normalized, null, 2),
      threat_coverage_report: threatCoverageMarkdown,
      intelligence_review: intelligenceReviewMarkdown,
      customer_delivery_pack: customerDeliveryPackMarkdown,
      platform_export: JSON.stringify(platformContent, null, 2),
      full_package: JSON.stringify(fullPackage, null, 2),
      documentation: adapterDocumentation,
      connector_checklist: connectorChecklist,
      customer_documentation: customerDocMarkdown,
      // Internal
      _status: fortiPkg.metadata.status,
      _readinessChecks: fortiPkg.readinessChecks,
      _platformFileName: platformFileName,
      _slug: slug,
      _customerDoc: customerDoc,
      _customerDocHTML: customerDocHTML,
      _threatCoverage: threatCoverage,
      _intelligenceReview: intelligenceReview,
    };
  }, [playbook, deploymentProfile, targetPlatform]);


  const exportReadiness = useMemo(() => {
    const normalized = buildNormalizedPlaybook(playbook, targetPlatform);
    const adapter = getPlatformAdapter(targetPlatform);
    const readiness = adapter.validateReadiness(
      normalized,
      {
        ...(deploymentProfile ?? {}),
        _playbookState: playbook,
      },
    );

    return evaluateExportReadiness(normalized, targetPlatform, readiness);
  }, [playbook, deploymentProfile, targetPlatform]);

  const threatCoverage = useMemo(() => {
    const normalized = buildNormalizedPlaybook(playbook, targetPlatform);
    return analyzeThreatCoverage(playbook, normalized, targetPlatform);
  }, [playbook, targetPlatform]);

  const intelligenceReview = useMemo(() => {
    const normalized = buildNormalizedPlaybook(playbook, targetPlatform);
    return analyzePlaybookIntelligence({
      playbook,
      normalized,
      targetPlatform,
      threatCoverage,
      exportReadiness,
    });
  }, [playbook, targetPlatform, threatCoverage, exportReadiness]);

  const exportCards = buildExportCards(targetPlatform);
  const pMeta = PLATFORM_EXPORT_META[targetPlatform] ?? PLATFORM_EXPORT_META.generic_soar;

  const handleCopy = (type: FixedExportType) => {
    navigator.clipboard.writeText(exports[type]);
    setCopied(type);
    setTimeout(() => setCopied(null), 2000);
  };

  const handleDownload = (type: FixedExportType) => {
    let filename: string;
    let mime: string;

    if (type === 'platform_export') {
      filename = exports._platformFileName;
      mime = 'application/json';
    } else if (type === 'documentation') {
      filename = `${exports._slug}_documentation.md`;
      mime = 'text/markdown';
    } else if (type === 'connector_checklist') {
      filename = `${exports._slug}_connector_checklist.md`;
      mime = 'text/markdown';
    } else if (type === 'normalized_blueprint') {
      filename = `${exports._slug}_normalized_soar_blueprint.json`;
      mime = 'application/json';
    } else if (type === 'threat_coverage_report') {
      filename = `${exports._slug}_threat_coverage_report.md`;
      mime = 'text/markdown';
    } else if (type === 'intelligence_review') {
      filename = `${exports._slug}_soarforge_intelligence_review.md`;
      mime = 'text/markdown';
    } else if (type === 'customer_delivery_pack') {
      filename = `${exports._slug}_customer_delivery_pack.md`;
      mime = 'text/markdown';
    } else if (type === 'full_package') {
      filename = `${exports._slug}_${targetPlatform}_full_deployment_package.json`;
      mime = 'application/json';
    } else if (type === 'customer_documentation') {
      filename = `${exports._slug}_customer_implementation_guide.md`;
      mime = 'text/markdown';
    } else {
      filename = `${exports._slug}_project_state.json`;
      mime = 'application/json';
    }

    const blob = new Blob([exports[type]], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleCopyPlaceholder = (connectorKey: string) => {
    const placeholder = `{{CUSTOMER_${connectorKey.toUpperCase()}_CONFIG_UUID}}`;
    navigator.clipboard.writeText(placeholder);
    setCopiedConnector(connectorKey + '_placeholder');
    setTimeout(() => setCopiedConnector(null), 2000);
  };

  const handleDownloadCustomerHTML = () => {
    const html = exports._customerDocHTML;
    const slug = exports._slug;
    const filename = `${slug}_customer_implementation_guide.html`;
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const statusMeta = STATUS_META[exports._status] ?? STATUS_META.draft;
  const StatusIcon = statusMeta.icon;
  const criticalIssues = exports._readinessChecks.filter((c) => c.critical && !c.passed);
  const warnings = exports._readinessChecks.filter((c) => !c.critical && !c.passed);

  const selectedCard = exportCards.find((c) => c.type === selectedExport) ?? exportCards[0];
  const isNonFortiSOAR = targetPlatform !== 'fortisoar';

  return (
    <div className="min-h-screen bg-background">
      <ConnectorConfigModal />

      <div className="max-w-5xl mx-auto p-8">
        <button
          onClick={() => { setIsExporting(false); setCurrentStep(11); }}
          className="flex items-center gap-2 text-accent hover:text-accent/80 mb-8 transition-colors text-sm"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Wizard
        </button>

        <div className="space-y-8">
          <div>
            <h1 className="text-3xl font-bold mb-1">Export Center</h1>
            <p className="text-muted-foreground text-sm">Download your completed SOAR playbook package</p>
            <div className="mt-3 flex items-center gap-3 flex-wrap">
              <span className="text-sm font-medium text-foreground">Target Platform:</span>
              <PlatformExportBadge platform={targetPlatform} />
            </div>
          </div>

          {/* Status Banner */}
          <Card className={`p-5 ${statusMeta.bg} ${statusMeta.border} border`}>
            <div className="flex items-start gap-4">
              <StatusIcon className={`w-5 h-5 ${statusMeta.text} shrink-0 mt-0.5`} />
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-3 mb-1 flex-wrap">
                  <h3 className={`font-semibold ${statusMeta.text}`}>
                    Status: {exports._status.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())}
                  </h3>
                  {isNonFortiSOAR && (
                    <span className="text-xs px-2 py-0.5 rounded border border-accent/30 bg-accent/10 text-accent">
                      {pMeta.title}
                    </span>
                  )}
                </div>
                <p className="text-sm text-muted-foreground">
                  {exports._status === 'draft' && 'Complete the wizard steps to enable export.'}
                  {exports._status === 'ready_for_configuration' && 'Template loaded. Configure connector details before deploying.'}
                  {exports._status === 'ready_for_uat' && isNonFortiSOAR && 'Blueprint generated. Verify integrations and actions in your tenant before use.'}
                  {exports._status === 'ready_for_uat' && !isNonFortiSOAR && 'Ready for UAT testing. Replace template placeholders with actual UUIDs for production import.'}
                  {exports._status === 'ready_for_import' && !isNonFortiSOAR && 'All checks pass. Workflow can be imported to FortiSOAR for testing.'}
                  {exports._status === 'ready_for_import' && isNonFortiSOAR && 'Blueprint ready. Verify all integration references in your tenant before deployment.'}
                  {exports._status === 'production_ready' && 'Verified and approved for production deployment.'}
                </p>
                {(criticalIssues.length > 0 || warnings.length > 0) && (
                  <div className="mt-3 flex flex-wrap gap-2">
                    {criticalIssues.length > 0 && (
                      <span className="inline-flex items-center gap-1 px-2 py-0.5 text-xs bg-red-900/30 text-red-400 rounded border border-red-800/30">
                        <XCircle className="w-3 h-3" />
                        {criticalIssues.length} critical issue{criticalIssues.length !== 1 ? 's' : ''}
                      </span>
                    )}
                    {warnings.length > 0 && (
                      <span className="inline-flex items-center gap-1 px-2 py-0.5 text-xs bg-yellow-900/20 text-yellow-400 rounded border border-yellow-800/30">
                        <AlertTriangle className="w-3 h-3" />
                        {warnings.length} warning{warnings.length !== 1 ? 's' : ''}
                      </span>
                    )}
                  </div>
                )}
              </div>
            </div>
          </Card>

          <ExportReadinessPanel result={exportReadiness} />
          <ThreatCoveragePanel result={threatCoverage} />
          <IntelligenceReviewPanel result={intelligenceReview} />

          {/* Export Type Selector */}
          <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
            {exportCards.map((card) => (
              <button
                key={card.type}
                onClick={() => setSelectedExport(card.type)}
                className={`p-4 rounded-lg border text-left transition-all ${
                  selectedExport === card.type ? 'border-accent bg-accent/10' : 'border-border hover:border-muted-foreground/50'
                }`}
              >
                <div className="font-medium text-sm mb-1">{card.title}</div>
                <div className="text-xs text-muted-foreground">{card.subtitle}</div>
              </button>
            ))}
          </div>

          {/* Selected Export Panel */}
          <Card className="p-6">
            <div className="flex items-start justify-between mb-4 gap-4">
              <div>
                <h3 className="text-lg font-semibold">{selectedCard.title}</h3>
                <p className="text-sm text-muted-foreground mt-1">{selectedCard.description}</p>
              </div>
              <div className="flex gap-2 shrink-0 flex-wrap">
                <Button onClick={() => handleCopy(selectedExport)} variant="outline" size="sm" className="gap-2">
                  <Copy className="w-4 h-4" />
                  {copied === selectedExport ? 'Copied!' : 'Copy'}
                </Button>
                <Button onClick={() => handleDownload(selectedExport)} size="sm" className="gap-2">
                  <Download className="w-4 h-4" />
                  {selectedExport === 'customer_documentation' ? 'Download MD' : 'Download'}
                </Button>
                {selectedExport === 'customer_documentation' && (
                  <Button onClick={handleDownloadCustomerHTML} variant="outline" size="sm" className="gap-2">
                    <Download className="w-4 h-4" />
                    Download HTML
                  </Button>
                )}
              </div>
            </div>

            {/* Filename label */}
            <div className="mb-3 px-3 py-1.5 bg-muted/50 rounded border border-border text-xs font-mono text-muted-foreground">
              {selectedExport === 'platform_export' && exports._platformFileName}
              {selectedExport === 'documentation' && `${exports._slug}_documentation.md`}
              {selectedExport === 'connector_checklist' && `${exports._slug}_connector_checklist.md`}
              {selectedExport === 'normalized_blueprint' && `${exports._slug}_normalized_soar_blueprint.json`}
              {selectedExport === 'threat_coverage_report' && `${exports._slug}_threat_coverage_report.md`}
              {selectedExport === 'intelligence_review' && `${exports._slug}_soarforge_intelligence_review.md`}
              {selectedExport === 'customer_delivery_pack' && `${exports._slug}_customer_delivery_pack.md`}
              {selectedExport === 'full_package' && `${exports._slug}_${targetPlatform}_full_deployment_package.json`}
              {selectedExport === 'project_state' && `${exports._slug}_project_state.json`}
              {selectedExport === 'customer_documentation' && `${exports._slug}_customer_implementation_guide.md`}
            </div>

            {/* Preview - use special component for customer documentation */}
            {selectedExport === 'customer_documentation' ? (
              <DocumentationPreview document={exports._customerDoc} />
            ) : (
              <div className="bg-muted rounded-lg p-4 font-mono text-xs overflow-auto max-h-80 border border-border">
                <pre className="whitespace-pre-wrap">
                  {exports[selectedExport].split('\n').slice(0, 40).join('\n')}
                  {exports[selectedExport].split('\n').length > 40 && '\n\n... (truncated — download to view full output)'}
                </pre>
              </div>
            )}

            {/* Non-FortiSOAR blueprint warning */}
            {selectedExport === 'platform_export' && isNonFortiSOAR && (
              <div className="mt-4 p-3 bg-blue-900/20 border border-blue-700/30 rounded-lg flex items-start gap-3">
                <Info className="w-5 h-5 text-blue-400 shrink-0 mt-0.5" />
                <div className="text-sm">
                  <p className="font-medium text-blue-300 mb-1">Blueprint Export</p>
                  <p className="text-blue-200/80">{pMeta.description}</p>
                </div>
              </div>
            )}

            {/* FortiSOAR not-ready warning */}
            {selectedExport === 'platform_export' && !isNonFortiSOAR && exports._status !== 'ready_for_import' && (
              <div className="mt-4 p-3 bg-yellow-900/20 border border-yellow-700/30 rounded-lg flex items-start gap-3">
                <AlertTriangle className="w-5 h-5 text-yellow-500 shrink-0 mt-0.5" />
                <div className="text-sm">
                  <p className="font-medium text-yellow-400 mb-1">Not ready for import</p>
                  <p className="text-yellow-200/80">
                    {exports._status === 'draft' && 'Complete the wizard steps first.'}
                    {exports._status === 'ready_for_configuration' && 'Configure all connector UUIDs with valid values (not fake/test strings).'}
                    {exports._status === 'ready_for_uat' && 'Replace all template placeholders with actual values before importing to production.'}
                  </p>
                </div>
              </div>
            )}
          </Card>

          {/* Critical Issues */}
          {criticalIssues.length > 0 && (
            <Card className="p-6">
              <h3 className="font-semibold text-red-400 mb-4 flex items-center gap-2">
                <XCircle className="w-4 h-4" />
                Critical Issues ({criticalIssues.length})
              </h3>
              <div className="space-y-2">
                {criticalIssues.map((check) => (
                  <div key={check.id} className="flex items-start gap-3 p-3 bg-red-900/10 rounded-lg border border-red-900/30">
                    <XCircle className="w-4 h-4 text-red-500 shrink-0 mt-0.5" />
                    <div className="min-w-0">
                      <p className="text-sm font-medium">{check.label}</p>
                      {check.note && <p className="text-xs text-muted-foreground mt-0.5">{check.note}</p>}
                      {check.fixConnectorKey && (
                        <Button
                          onClick={() => openConnectorModal(check.fixConnectorKey)}
                          size="sm"
                          variant="outline"
                          className="mt-2 gap-2 text-xs h-7"
                        >
                          <Settings className="w-3 h-3" />
                          Configure UUID
                        </Button>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </Card>
          )}

          {/* Connector Configuration Status — FortiSOAR only */}
          {!isNonFortiSOAR && (
            <Card className="p-6">
              <h3 className="font-semibold mb-4">Connector Configuration Status</h3>
              <div className="space-y-2">
                {Object.entries(deploymentProfile?.connectors ?? {}).map(([key, connector]) => {
                  const cfg = connector as { config: string; displayName: string; operation?: string; operationTitle?: string };
                  const status = validateConfigValue(cfg.config);
                  const statusClass = CONNECTOR_STATUS_COLORS[status];
                  const isPlaceholderCopied = copiedConnector === key + '_placeholder';

                  return (
                    <div key={key} className="flex items-center justify-between gap-3 p-3 bg-muted/40 rounded-lg border border-border">
                      <div className="min-w-0 flex-1">
                        <div className="flex items-center gap-2 flex-wrap">
                          <p className="font-medium text-sm">{cfg.displayName}</p>
                          <span className={`px-2 py-0.5 text-xs rounded border ${statusClass}`}>
                            {CONNECTOR_STATUS_LABEL[status]}
                            {status === 'fake' && ' — must fix'}
                          </span>
                        </div>
                        <p className="text-xs text-muted-foreground font-mono truncate mt-0.5 max-w-xs">
                          {cfg.config || '(not set)'}
                        </p>
                        {cfg.operation && (
                          <p className="text-xs text-muted-foreground mt-0.5">
                            Operation: <span className="font-mono">{cfg.operation}</span>
                          </p>
                        )}
                      </div>

                      <div className="flex items-center gap-1.5 shrink-0">
                        <Button
                          onClick={() => openConnectorModal(key)}
                          size="sm"
                          variant="outline"
                          className="gap-1.5 text-xs h-7 px-2"
                          title="Configure UUID"
                        >
                          <Settings className="w-3 h-3" />
                          UUID
                        </Button>
                        <Button
                          onClick={() => { openConnectorModal(key); }}
                          size="sm"
                          variant="outline"
                          className="gap-1.5 text-xs h-7 px-2"
                          title="Edit Operation"
                        >
                          <Pencil className="w-3 h-3" />
                          Op
                        </Button>
                        <Button
                          onClick={() => handleCopyPlaceholder(key)}
                          size="sm"
                          variant="ghost"
                          className="gap-1.5 text-xs h-7 px-2"
                          title="Copy placeholder to clipboard"
                        >
                          <ClipboardCopy className="w-3 h-3" />
                          {isPlaceholderCopied ? 'Copied!' : 'Placeholder'}
                        </Button>
                      </div>
                    </div>
                  );
                })}
              </div>
              <p className="text-xs text-muted-foreground mt-3">
                UUID — set the FortiSOAR config instance UUID. Op — override the connector operation name. Placeholder — copy the template variable to clipboard.
              </p>
            </Card>
          )}

          {/* Warnings (non-critical) */}
          {warnings.length > 0 && (
            <Card className="p-6">
              <h3 className="font-semibold text-yellow-400 mb-4 flex items-center gap-2">
                <AlertTriangle className="w-4 h-4" />
                Warnings ({warnings.length})
              </h3>
              <div className="space-y-2">
                {warnings.map((check) => (
                  <div key={check.id} className="flex items-start gap-3 p-3 bg-yellow-900/10 rounded-lg border border-yellow-900/20">
                    <AlertTriangle className="w-4 h-4 text-yellow-500 shrink-0 mt-0.5" />
                    <div className="min-w-0">
                      <p className="text-sm font-medium">{check.label}</p>
                      {check.note && <p className="text-xs text-muted-foreground mt-0.5">{check.note}</p>}
                    </div>
                  </div>
                ))}
              </div>
            </Card>
          )}

          {/* QA Matrix Report */}
          <QAMatrixReport playbook={playbook} deploymentProfile={deploymentProfile} />
        </div>
      </div>
    </div>
  );
}

// ============================================================================
// QA Matrix Report Component
// ============================================================================

import type { PlaybookState } from '@/lib/soar-types';
import type { FortiSOARDeploymentProfile } from '@/lib/fortisoar-types';

function QAMatrixReport({
  playbook,
  deploymentProfile,
}: {
  playbook: PlaybookState;
  deploymentProfile: FortiSOARDeploymentProfile;
}) {
  const templateId = playbook.templateId || playbook.generatorType || '';
  const qaEntry = SOAR_QA_MATRIX.find((e) => e.templateId === templateId);

  if (!qaEntry) {
    return (
      <Card className="p-6">
        <div className="flex items-center gap-2 mb-3">
          <ShieldCheck className="w-5 h-5 text-muted-foreground" />
          <h3 className="font-semibold">QA Matrix</h3>
        </div>
        <p className="text-sm text-muted-foreground">
          QA matrix validation is available for predefined templates only. Custom templates do not have expected step sets.
        </p>
      </Card>
    );
  }

  const qaRow: QAReportRow = useMemo(() => {
    try {
      const collection = generateFortiSOARWorkflowCollection(playbook, deploymentProfile);
      const workflow = collection.data[0]?.workflows[0];
      const stepNames = workflow?.steps.map((s) => s.name) ?? [];
      return runQAReportRow(templateId, stepNames);
    } catch {
      return runQAReportRow(templateId, []);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [templateId, playbook, deploymentProfile]);

  const passed = qaRow.status === 'pass';
  const allConnectors = qaRow.requiredConnectors;

  return (
    <Card className="p-6">
      <div className="flex items-center justify-between mb-4 flex-wrap gap-2">
        <div className="flex items-center gap-2">
          <ShieldCheck className={`w-5 h-5 ${passed ? 'text-green-400' : 'text-red-400'}`} />
          <h3 className="font-semibold">QA Matrix Report</h3>
        </div>
        <span className={`px-2.5 py-0.5 text-xs font-medium rounded border ${
          passed
            ? 'bg-green-900/20 border-green-800/30 text-green-400'
            : 'bg-red-900/20 border-red-800/30 text-red-400'
        }`}>
          {passed ? 'PASS' : 'FAIL'}
        </span>
      </div>

      <div className="overflow-x-auto rounded-lg border border-border mb-4">
        <table className="w-full text-xs">
          <thead>
            <tr className="border-b border-border bg-muted/40">
              <th className="text-left px-3 py-2 font-medium text-muted-foreground">Template</th>
              <th className="text-left px-3 py-2 font-medium text-muted-foreground">Generator</th>
              <th className="text-left px-3 py-2 font-medium text-muted-foreground">Expected Steps</th>
              <th className="text-left px-3 py-2 font-medium text-muted-foreground">Required Connectors</th>
              <th className="text-left px-3 py-2 font-medium text-muted-foreground">Guardrails</th>
              <th className="text-left px-3 py-2 font-medium text-muted-foreground">Status</th>
            </tr>
          </thead>
          <tbody>
            <tr className="border-b border-border/50">
              <td className="px-3 py-2.5 font-medium">{qaRow.templateName}</td>
              <td className="px-3 py-2.5 font-mono text-muted-foreground">{qaRow.generatorFunction}</td>
              <td className="px-3 py-2.5 text-muted-foreground">
                {qaRow.presentStepCount}/{qaRow.expectedStepCount} present
              </td>
              <td className="px-3 py-2.5">
                <div className="flex flex-wrap gap-1">
                  {allConnectors.map((c) => {
                    const cfg = deploymentProfile?.connectors[c];
                    const isConfigured = cfg && cfg.isConfigured;
                    return (
                      <span key={c} className={`px-1.5 py-0.5 rounded text-[10px] border ${
                        isConfigured
                          ? 'bg-green-900/20 border-green-800/30 text-green-400'
                          : 'bg-gray-800/40 border-gray-700/30 text-gray-400'
                      }`}>
                        {c}
                      </span>
                    );
                  })}
                </div>
              </td>
              <td className="px-3 py-2.5 text-muted-foreground">{qaRow.guardrailCount} defined</td>
              <td className="px-3 py-2.5">
                {passed ? (
                  <span className="flex items-center gap-1 text-green-400">
                    <CheckCircle className="w-3 h-3" /> Pass
                  </span>
                ) : (
                  <span className="flex items-center gap-1 text-red-400">
                    <XCircle className="w-3 h-3" /> Fail
                  </span>
                )}
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      {qaRow.missingMustContain.length > 0 && (
        <div className="mb-3 p-3 bg-red-900/10 border border-red-900/30 rounded-lg">
          <p className="text-xs font-medium text-red-400 mb-1.5">Missing required steps (mustContain):</p>
          <div className="flex flex-wrap gap-1.5">
            {qaRow.missingMustContain.map((s) => (
              <span key={s} className="px-2 py-0.5 text-xs font-mono bg-red-900/20 border border-red-800/30 text-red-300 rounded">
                {s}
              </span>
            ))}
          </div>
        </div>
      )}

      {qaRow.forbiddenPresent.length > 0 && (
        <div className="mb-3 p-3 bg-red-900/10 border border-red-900/30 rounded-lg">
          <p className="text-xs font-medium text-red-400 mb-1.5">Forbidden steps found (mustNotContain):</p>
          <div className="flex flex-wrap gap-1.5">
            {qaRow.forbiddenPresent.map((s) => (
              <span key={s} className="px-2 py-0.5 text-xs font-mono bg-red-900/20 border border-red-800/30 text-red-300 rounded">
                {s}
              </span>
            ))}
          </div>
        </div>
      )}

      <details className="text-xs">
        <summary className="cursor-pointer text-muted-foreground hover:text-foreground transition-colors py-1 select-none">
          View {qaEntry.guardrails.length} defined guardrails
        </summary>
        <ul className="mt-2 space-y-1 pl-2 border-l border-border">
          {qaEntry.guardrails.map((g, i) => (
            <li key={i} className="text-muted-foreground">{g}</li>
          ))}
        </ul>
      </details>

      {passed && (
        <p className="mt-3 text-xs text-green-400">
          All required steps present. No forbidden steps detected. Template uses a real generator (not generic workflow).
        </p>
      )}
    </Card>
  );
}

// ── Documentation helpers ────────────────────────────────────────────────────

function buildFortiSOARDocumentation(pkg: FortiSOARExportPackage): string {
  return [
    pkg.documentation.implementationGuide,
    pkg.documentation.uatTestPlan,
    pkg.documentation.rollbackPlan,
    pkg.documentation.connectorMatrix,
    pkg.documentation.mitreMapping,
    pkg.documentation.knownLimitations,
  ].join('\n\n---\n\n');
}

function buildFortiSOARConnectorChecklist(profile: FortiSOARDeploymentProfile | null): string {
  if (!profile) return '# Connector Checklist\n\nNo deployment profile available.';
  const lines = ['# FortiSOAR Connector Configuration Checklist\n'];
  for (const [key, conn] of Object.entries(profile.connectors ?? {})) {
    const c = conn as { displayName: string; config: string; isConfigured?: boolean };
    lines.push(`## ${c.displayName}`);
    lines.push(`- Key: \`${key}\``);
    lines.push(`- Config value: \`${c.config || '(not set)'}\``);
    lines.push(`- Configured: ${c.isConfigured ? 'Yes' : 'No'}\n`);
  }
  return lines.join('\n');
}
