// ============================================================
// SOARForge — Defensive Detection Logic Library
// Safe, defensive examples only. No exploit or malware code.
// ============================================================

import type { DetectionLogicRecord } from './threat-knowledge-types';

export const DETECTION_LOGIC_LIBRARY: DetectionLogicRecord[] = [
  {
    detectionId: 'det-ransomware-file-impact',
    title: 'Ransomware-like File Activity Pattern',
    description: 'Detects high-volume file changes with suspicious extension or ransom-note indicators using endpoint telemetry.',
    techniqueIds: ['T1486'],
    incidentTypeIds: ['ransomware'],
    logSources: ['EDR file activity', 'Windows file auditing', 'Endpoint process telemetry'],
    requiredFields: ['hostname', 'file_path', 'process_name', 'timestamp'],
    severity: 'critical',
    falsePositiveFilters: ['approved backup software', 'enterprise encryption tools', 'maintenance windows'],
    tuningNotes: ['Baseline normal file-change volume per server role before enabling automatic containment.'],
    queries: {
      generic: 'File activity spike + suspicious extension/ransom-note marker + unusual process context',
      sigma: 'title: Ransomware-like File Activity Pattern\nlogsource:\n  category: file_event\ndetection:\n  selection:\n    TargetFilename|contains: [".locked", ".encrypted", "README"]\n  condition: selection',
      kql: 'DeviceFileEvents | where FileName has_any (".locked", ".encrypted", "README") | summarize Count=count() by DeviceName, InitiatingProcessFileName, bin(Timestamp, 5m)',
      spl: 'index=edr sourcetype=file_event (file_name="*.locked" OR file_name="*.encrypted" OR file_name="*README*") | stats count by host process_name',
    },
    status: 'Approved_For_Production',
  },
  {
    detectionId: 'det-shadow-copy-change',
    title: 'Recovery Control Alteration',
    description: 'Identifies command-line activity associated with recovery configuration changes.',
    techniqueIds: ['T1490'],
    incidentTypeIds: ['ransomware'],
    logSources: ['Windows Security 4688', 'Sysmon Process Create', 'EDR process telemetry'],
    requiredFields: ['hostname', 'username', 'process_name', 'command_line'],
    severity: 'high',
    falsePositiveFilters: ['backup administration tasks', 'approved maintenance change'],
    tuningNotes: ['Require parent process and user context before automatic containment.'],
    queries: {
      generic: 'Process command line contains recovery-control utility terms and runs outside approved maintenance context',
      kql: 'DeviceProcessEvents | where ProcessCommandLine has_any ("vssadmin", "wbadmin", "bcdedit") and ProcessCommandLine has_any ("delete", "disable", "recoveryenabled")',
      spl: 'index=windows EventCode=4688 (CommandLine="*vssadmin*" OR CommandLine="*wbadmin*" OR CommandLine="*bcdedit*")',
    },
    status: 'Approved_For_Production',
  },
  {
    detectionId: 'det-suspicious-powershell',
    title: 'Suspicious PowerShell Execution Context',
    description: 'Detects PowerShell execution patterns that require analyst review while allowing administrative false-positive tuning.',
    techniqueIds: ['T1059', 'T1059.001'],
    incidentTypeIds: ['ransomware', 'malware_hash'],
    logSources: ['PowerShell logs', 'Windows Security 4688', 'EDR process telemetry'],
    requiredFields: ['hostname', 'username', 'command_line', 'parent_process'],
    severity: 'medium',
    falsePositiveFilters: ['SCCM', 'Intune', 'signed admin scripts', 'approved IT automation'],
    tuningNotes: ['Do not isolate based on scripting alone; require additional evidence.'],
    queries: {
      sigma: 'title: Suspicious PowerShell Execution Context\nlogsource:\n  category: process_creation\n  product: windows\ndetection:\n  selection:\n    Image|endswith: "\\powershell.exe"\n    CommandLine|contains: ["-enc", "Bypass", "Hidden"]\n  condition: selection',
      kql: 'DeviceProcessEvents | where FileName =~ "powershell.exe" and ProcessCommandLine has_any ("-enc", "Bypass", "Hidden")',
      spl: 'index=windows EventCode=4688 Image="*\\powershell.exe" (CommandLine="*-enc*" OR CommandLine="*Bypass*" OR CommandLine="*Hidden*")',
    },
    status: 'Approved_For_Production',
  },

  {
    detectionId: 'det-phishing-url-reputation',
    title: 'Suspicious URL Reputation and Click Context',
    description: 'Correlates email URLs with click telemetry and reputation context before recommending quarantine or notification.',
    techniqueIds: ['T1566.002', 'T1204'],
    incidentTypeIds: ['phishing'],
    logSources: ['Email Gateway', 'URL Click Logs', 'Proxy Logs', 'Browser Telemetry'],
    requiredFields: ['sender_email', 'recipient_email', 'url', 'message_id', 'timestamp'],
    severity: 'high',
    falsePositiveFilters: ['approved awareness simulation', 'known partner portal', 'marketing platform redirect'],
    tuningNotes: ['Require message_id or campaign identifier before mailbox-wide remediation.'],
    queries: {
      generic: 'Email URL + reputation context + recipient click event + non-allowlisted sender domain',
      kql: 'EmailUrlInfo | join kind=leftouter UrlClickEvents on Url | summarize Clicks=count() by SenderFromAddress, RecipientEmailAddress, Url, NetworkMessageId',
      spl: 'index=email url=* | stats values(recipient) as recipients count by sender url message_id',
    },
    status: 'Approved_For_Production',
  },
  {
    detectionId: 'det-phishing-attachment-hash',
    title: 'Attachment Hash and Sandbox Review',
    description: 'Reviews attachment hash, file type, and sandbox verdict before recommending containment actions.',
    techniqueIds: ['T1566.001'],
    incidentTypeIds: ['phishing'],
    logSources: ['Email Gateway', 'Attachment Metadata', 'Sandbox Verdict', 'Threat Intelligence'],
    requiredFields: ['sender_email', 'recipient_email', 'attachment_hash', 'message_id'],
    severity: 'high',
    falsePositiveFilters: ['known business document workflow', 'signed internal attachment', 'approved partner attachment'],
    tuningNotes: ['Do not delete messages based only on attachment extension; require reputation or sandbox context.'],
    queries: {
      generic: 'Attachment hash present + suspicious file type + sandbox/reputation verdict + campaign search context',
      kql: 'EmailAttachmentInfo | where SHA256 != "" | summarize Recipients=dcount(RecipientEmailAddress), Messages=dcount(NetworkMessageId) by SenderFromAddress, SHA256, FileName',
      spl: 'index=email attachment_hash=* | stats dc(recipient) as recipients count by sender attachment_hash file_name',
    },
    status: 'Approved_For_Production',
  },
  {
    detectionId: 'det-phishing-sender-authentication',
    title: 'Sender Authentication and Domain Review',
    description: 'Reviews sender domain, SPF/DKIM/DMARC posture, and known partner context for phishing triage.',
    techniqueIds: ['T1566'],
    incidentTypeIds: ['phishing'],
    logSources: ['Email Gateway', 'DMARC Reports', 'Mailbox Audit'],
    requiredFields: ['sender_email', 'sender_domain', 'spf_result', 'dkim_result', 'dmarc_result'],
    severity: 'medium',
    falsePositiveFilters: ['known partner domain', 'approved bulk sender', 'internal relay'],
    tuningNotes: ['Use authentication failure as supporting context, not as the only remediation trigger.'],
    queries: {
      generic: 'External sender + failed authentication + suspicious subject/link/attachment context',
      kql: 'EmailEvents | where SenderFromDomain != "" | summarize Count=count() by SenderFromDomain, AuthenticationDetails, DeliveryAction',
      spl: 'index=email | stats count by sender_domain spf dkim dmarc action',
    },
    status: 'Approved_For_Production',
  },
  {
    detectionId: 'det-phishing-campaign-search',
    title: 'Mailbox Campaign Search and Duplicate Message Guardrail',
    description: 'Identifies similar messages across mailboxes while enforcing unique message identifiers for safe remediation.',
    techniqueIds: ['T1566'],
    incidentTypeIds: ['phishing'],
    logSources: ['Mailbox Audit', 'Email Gateway', 'Message Trace'],
    requiredFields: ['message_id', 'sender_email', 'subject_line', 'recipient_email'],
    severity: 'high',
    falsePositiveFilters: ['newsletter campaign', 'security awareness campaign', 'approved business announcement'],
    tuningNotes: ['Quarantine by unique message_id where possible and keep release/rollback available.'],
    queries: {
      generic: 'Same sender/subject/url/hash across multiple recipients with unique message identifier tracking',
      kql: 'EmailEvents | summarize Recipients=dcount(RecipientEmailAddress), Messages=dcount(NetworkMessageId) by SenderFromAddress, Subject',
      spl: 'index=email | stats dc(recipient) as recipients dc(message_id) as messages by sender subject',
    },
    status: 'Approved_For_Production',
  },
  {
    detectionId: 'det-password-spray',
    title: 'Repeated Authentication Attempts Across Users',
    description: 'Identifies distributed authentication failures from a single source against multiple accounts.',
    techniqueIds: ['T1110.003'],
    incidentTypeIds: ['suspicious_login'],
    logSources: ['Azure AD sign-in logs', 'Okta logs', 'VPN authentication logs'],
    requiredFields: ['source_ip', 'username', 'result', 'timestamp'],
    severity: 'high',
    falsePositiveFilters: ['legacy sync client', 'password expiration wave', 'known VPN egress'],
    tuningNotes: ['Use user count and failure ratio instead of raw failure count only.'],
    queries: {
      kql: 'SigninLogs | where ResultType != 0 | summarize Users=dcount(UserPrincipalName), Failures=count() by IPAddress, bin(TimeGenerated, 15m) | where Users >= 20 and Failures >= 50',
      spl: 'index=auth action=failure | stats dc(user) as users count as failures by src_ip | where users>=20 AND failures>=50',
      generic: 'Authentication failures from one source IP across many distinct accounts within a short time window',
    },
    status: 'Approved_For_Production',
  },
  {
    detectionId: 'det-waf-application-event',
    title: 'Public Application Security Event',
    description: 'Detects WAF rule activity requiring enrichment and context validation before blocking.',
    techniqueIds: ['T1190'],
    incidentTypeIds: ['waf_attack', 'vulnerability'],
    logSources: ['WAF logs', 'Application gateway logs', 'Web server logs'],
    requiredFields: ['client_ip', 'uri', 'method', 'status_code', 'waf_rule_id'],
    severity: 'high',
    falsePositiveFilters: ['internal scanner', 'approved penetration test', 'CDN edge IP'],
    tuningNotes: ['Always perform CDN/cloud ownership check before automatic blocking.'],
    queries: {
      generic: 'WAF high severity rule match + repeated requests + non-allowlisted source',
      kql: 'AzureDiagnostics | where Category has "ApplicationGatewayFirewallLog" | where action_s in ("Blocked", "Matched") | summarize Count=count() by clientIp_s, requestUri_s, ruleId_s',
      spl: 'index=waf (action=blocked OR action=matched) | stats count by src_ip uri rule_id',
    },
    status: 'Approved_For_Production',
  },
  {
    detectionId: 'det-c2-beaconing',
    title: 'Unusual Network Communication Pattern',
    description: 'Detects periodic outbound network behavior for review with threat-intelligence context.',
    techniqueIds: ['T1071'],
    incidentTypeIds: ['malicious_ip', 'threat_intel'],
    logSources: ['DNS logs', 'Proxy logs', 'Firewall logs', 'NetFlow'],
    requiredFields: ['source_ip', 'destination_ip', 'domain', 'timestamp'],
    severity: 'high',
    falsePositiveFilters: ['EDR telemetry', 'SaaS agent traffic', 'software update services'],
    tuningNotes: ['Use reputation and internal asset context before blocking.'],
    queries: {
      generic: 'Periodic outbound communication with low variance interval and suspicious reputation context',
      spl: 'index=proxy OR index=dns | bucket _time span=5m | stats count by src_ip dest domain _time',
    },
    status: 'Approved_For_Production',
  },
  {
    detectionId: 'det-mailbox-rule-change',
    title: 'Suspicious Mailbox Rule Change',
    description: 'Detects external forwarding or unusual mailbox rule creation requiring identity review.',
    techniqueIds: ['T1098'],
    incidentTypeIds: ['phishing', 'suspicious_login'],
    logSources: ['O365 audit logs', 'Exchange audit logs'],
    requiredFields: ['username', 'email', 'rule_name', 'forward_to'],
    severity: 'high',
    falsePositiveFilters: ['approved assistant delegation', 'known workflow mailbox', 'ticketed forwarding request'],
    tuningNotes: ['Confirm external destination and recent login risk before deleting rules.'],
    queries: {
      kql: 'OfficeActivity | where Operation has_any ("New-InboxRule", "Set-InboxRule") | where Parameters has_any ("ForwardTo", "RedirectTo")',
      spl: 'index=o365 Operation IN (New-InboxRule, Set-InboxRule) Parameters="*ForwardTo*"',
    },
    status: 'Approved_For_Production',
  },
];

export function getDetectionLogicForIncident(incidentTypeId: string): DetectionLogicRecord[] {
  return DETECTION_LOGIC_LIBRARY.filter((d) => d.incidentTypeIds.includes(incidentTypeId));
}

export function getDetectionLogicForTechniques(techniqueIds: string[]): DetectionLogicRecord[] {
  return DETECTION_LOGIC_LIBRARY.filter((d) => d.techniqueIds.some((id) => techniqueIds.includes(id)));
}
