// ============================================================
// SOARForge — Incident to MITRE Mapping Library
// Phase 1 covers current templates + common SOC incidents.
// ============================================================

import type { IncidentMitreMapping } from './threat-knowledge-types';

export const INCIDENT_MITRE_MAPPINGS: Record<string, IncidentMitreMapping> = {
  ransomware: {
    incidentTypeId: 'ransomware',
    displayName: 'Ransomware Behavior',
    category: 'endpoint',
    description: 'Endpoint behavior indicating encryption, recovery alteration, or rapid file impact activity.',
    requiredTechniques: ['T1486', 'T1490'],
    optionalTechniques: ['T1059', 'T1059.001', 'T1562.001', 'T1048'],
    primaryTactics: ['Impact', 'Execution', 'Defense Evasion'],
    dataSources: ['EDR Telemetry', 'Process Creation', 'File Activity', 'Command Execution'],
    requiredEntities: ['hostname', 'machine_id', 'username', 'command_line', 'file_hash'],
    recommendedEnrichment: ['EDR asset lookup', 'Hash reputation', 'Recent process tree', 'User context'],
    recommendedResponses: ['Isolate endpoint', 'Collect forensic context', 'Disable account only with approval', 'Notify SOC'],
    approvalPoints: ['Disable privileged user', 'Contain business-critical server', 'Any action targeting domain controller'],
    rollbackActions: ['Unisolate endpoint', 'Re-enable AD account', 'Document containment reversal'],
    falsePositiveChecks: ['Backup job', 'Encryption software', 'Maintenance window', 'EDR false-positive verdict'],
    testScenarios: ['High-score synthetic alert', 'Low-score backup-like event', 'Missing machine_id fallback', 'Approval reject path'],
    confidence: 'high',
  },
  phishing: {
    incidentTypeId: 'phishing',
    displayName: 'Phishing Response',
    category: 'email',
    description: 'Suspicious email delivery involving URL, attachment, sender, or mailbox campaign indicators.',
    requiredTechniques: ['T1566'],
    optionalTechniques: ['T1566.001', 'T1566.002', 'T1204', 'T1059'],
    primaryTactics: ['Initial Access', 'Execution'],
    dataSources: ['Email Gateway', 'Mailbox Audit', 'URL Click Logs', 'Sandbox Verdict', 'User Reported Phishing'],
    requiredEntities: ['sender_email', 'recipient_email', 'subject_line', 'url', 'attachment_hash', 'message_id'],
    recommendedEnrichment: ['URL reputation', 'Attachment hash reputation', 'Sender domain review', 'Mailbox campaign search', 'Message authentication review'],
    recommendedResponses: ['Quarantine message', 'Block sender/domain with review', 'Notify recipients', 'Create ticket'],
    approvalPoints: ['Mass email deletion', 'External sender domain block', 'Mailbox-wide purge'],
    rollbackActions: ['Release quarantined email', 'Remove sender block', 'Document restoration'],
    falsePositiveChecks: ['Known partner domain', 'Marketing platform', 'Internal testing campaign', 'Approved security awareness simulation'],
    testScenarios: ['Credential-link payload', 'Attachment-hash payload', 'Known partner false positive', 'Mailbox search failure'],
    confidence: 'high',
  },
  suspicious_login: {
    incidentTypeId: 'suspicious_login',
    displayName: 'Suspicious Login',
    category: 'identity',
    description: 'Identity event requiring review of geography, device posture, MFA behavior, and session risk.',
    requiredTechniques: ['T1078'],
    optionalTechniques: ['T1110.003', 'T1098'],
    primaryTactics: ['Initial Access', 'Credential Access', 'Persistence'],
    dataSources: ['Identity Provider Logs', 'VPN Logs', 'Authentication Logs', 'Conditional Access Logs'],
    requiredEntities: ['username', 'upn', 'source_ip', 'geo', 'asn', 'mfa_status'],
    recommendedEnrichment: ['GeoIP', 'ASN reputation', 'User risk', 'Device compliance', 'Recent login history'],
    recommendedResponses: ['Revoke sessions', 'Force MFA reset', 'Create ticket', 'Notify identity team'],
    approvalPoints: ['Disable privileged user', 'Block shared VPN egress IP', 'Reset executive account'],
    rollbackActions: ['Restore session policy', 'Unlock or re-enable account after review'],
    falsePositiveChecks: ['VPN route', 'Business travel', 'Known proxy', 'Mobile roaming'],
    testScenarios: ['Impossible travel payload', 'VPN false positive', 'MFA fatigue payload', 'Missing geo data'],
    confidence: 'high',
  },
  waf_attack: {
    incidentTypeId: 'waf_attack',
    displayName: 'Web / WAF Security Event',
    category: 'web',
    description: 'Web-facing security event such as SQL injection, RCE, traversal, SSRF, bot, or API abuse pattern.',
    requiredTechniques: ['T1190'],
    optionalTechniques: ['T1059', 'T1071'],
    primaryTactics: ['Initial Access', 'Execution', 'Command and Control'],
    dataSources: ['WAF Logs', 'Web Server Logs', 'Application Logs', 'Firewall Logs'],
    requiredEntities: ['client_ip', 'uri', 'method', 'status_code', 'waf_rule_id', 'owasp_category'],
    recommendedEnrichment: ['IP reputation', 'ASN/CDN check', 'WAF rule context', 'Recent request volume'],
    recommendedResponses: ['Block IP with CDN guardrail', 'Create ticket', 'Notify application owner', 'Add WAF exception only with approval'],
    approvalPoints: ['Block CDN/shared IP', 'Change WAF policy', 'Add WAF exception'],
    rollbackActions: ['Remove IP block', 'Restore WAF policy', 'Document exception removal'],
    falsePositiveChecks: ['Internal scanner', 'Penetration test range', 'CDN edge IP', 'Health monitor'],
    testScenarios: ['SQLi-like safe payload', 'CDN IP false positive', 'High request volume', 'Missing URI field'],
    confidence: 'high',
  },
  malware_hash: {
    incidentTypeId: 'malware_hash',
    displayName: 'Suspicious Artifact / Hash Review',
    category: 'endpoint',
    description: 'Suspicious file hash, sandbox verdict, or malware alert requiring enrichment and containment review.',
    requiredTechniques: ['T1059'],
    optionalTechniques: ['T1003', 'T1562.001'],
    primaryTactics: ['Execution', 'Credential Access', 'Defense Evasion'],
    dataSources: ['EDR Telemetry', 'File Metadata', 'Sandbox Verdict', 'Hash Reputation'],
    requiredEntities: ['file_hash', 'file_path', 'hostname', 'machine_id', 'process_name'],
    recommendedEnrichment: ['VirusTotal lookup', 'Sandbox verdict', 'EDR prevalence', 'Process tree'],
    recommendedResponses: ['Quarantine file with approval', 'Collect process tree', 'Isolate endpoint if confidence is high'],
    approvalPoints: ['Delete/quarantine file', 'Isolate production server'],
    rollbackActions: ['Restore quarantined file', 'Unisolate endpoint'],
    falsePositiveChecks: ['Signed software', 'Known business app', 'Internal tool hash'],
    testScenarios: ['Known benign hash', 'Unknown suspicious hash', 'Sandbox unavailable', 'Missing endpoint ID'],
    confidence: 'medium',
  },
  malicious_ip: {
    incidentTypeId: 'malicious_ip',
    displayName: 'Malicious IP / C2 Communication',
    category: 'network',
    description: 'Network communication involving suspicious IP, beaconing, domain, or reputation-driven activity.',
    requiredTechniques: ['T1071'],
    optionalTechniques: ['T1048'],
    primaryTactics: ['Command and Control', 'Exfiltration'],
    dataSources: ['Firewall Logs', 'Proxy Logs', 'DNS Logs', 'NetFlow'],
    requiredEntities: ['source_ip', 'destination_ip', 'domain', 'hostname'],
    recommendedEnrichment: ['Threat intel reputation', 'ASN/CDN check', 'Internal asset lookup', 'DNS history'],
    recommendedResponses: ['Block IP/domain with context', 'Create ticket', 'Notify network team'],
    approvalPoints: ['Block shared/cloud IP', 'Block business SaaS domain'],
    rollbackActions: ['Unblock IP/domain', 'Document block rationale'],
    falsePositiveChecks: ['CDN/cloud provider', 'SaaS telemetry', 'Threat intel stale indicator'],
    testScenarios: ['Known suspicious IP payload', 'CDN false positive', 'Missing destination host'],
    confidence: 'high',
  },
  vulnerability: {
    incidentTypeId: 'vulnerability',
    displayName: 'Vulnerability Exposure',
    category: 'vulnerability',
    description: 'Critical vulnerability, internet exposure, or CISA KEV-related remediation workflow.',
    requiredTechniques: ['T1190'],
    optionalTechniques: [],
    primaryTactics: ['Initial Access'],
    dataSources: ['Vulnerability Scanner', 'CMDB', 'External Attack Surface Management', 'CISA KEV'],
    requiredEntities: ['cve_id', 'hostname', 'asset_id', 'business_owner', 'exposure_status'],
    recommendedEnrichment: ['Asset criticality', 'KEV match', 'Patch availability', 'Internet exposure'],
    recommendedResponses: ['Create patch ticket', 'Notify asset owner', 'Track exception approval'],
    approvalPoints: ['Patch exception', 'Emergency change', 'Compensating control'],
    rollbackActions: ['Close exception', 'Reopen ticket if validation fails'],
    falsePositiveChecks: ['Scanner stale result', 'Asset decommissioned', 'False external exposure'],
    testScenarios: ['KEV CVE payload', 'Stale scanner payload', 'Missing owner data'],
    confidence: 'medium',
  },
  threat_intel: {
    incidentTypeId: 'threat_intel',
    displayName: 'Threat Intelligence IOC Enrichment',
    category: 'threat_intel',
    description: 'Indicator enrichment and context-driven recommendation workflow.',
    requiredTechniques: ['T1071'],
    optionalTechniques: ['T1566', 'T1048'],
    primaryTactics: ['Command and Control', 'Initial Access'],
    dataSources: ['Threat Intel Feeds', 'SIEM', 'Proxy Logs', 'DNS Logs'],
    requiredEntities: ['ip', 'domain', 'url', 'file_hash'],
    recommendedEnrichment: ['Reputation lookup', 'Passive DNS', 'Internal sightings', 'Campaign tags'],
    recommendedResponses: ['Create intelligence note', 'Block only after context', 'Hunt across SIEM'],
    approvalPoints: ['Block indicator', 'Create global deny rule'],
    rollbackActions: ['Remove block', 'Mark IOC as expired'],
    falsePositiveChecks: ['Shared infrastructure', 'Stale IOC', 'SaaS provider IP'],
    testScenarios: ['Known IOC payload', 'Stale indicator payload', 'No internal sightings'],
    confidence: 'medium',
  },
  ticket_automation: {
    incidentTypeId: 'ticket_automation',
    displayName: 'Ticket Automation & ITSM Sync',
    category: 'operations',
    description: 'Operational workflow for incident ticket creation, enrichment, assignment, and closure tracking.',
    requiredTechniques: [],
    optionalTechniques: [],
    primaryTactics: [],
    dataSources: ['Case Management', 'ITSM', 'SOAR Records'],
    requiredEntities: ['record_id', 'severity', 'owner', 'sla'],
    recommendedEnrichment: ['Duplicate ticket check', 'Owner lookup', 'SLA calculation'],
    recommendedResponses: ['Create ticket', 'Update ticket', 'Notify owner'],
    approvalPoints: ['Close major incident', 'Change priority'],
    rollbackActions: ['Reopen ticket', 'Reassign owner'],
    falsePositiveChecks: ['Duplicate incident', 'Existing change request'],
    testScenarios: ['Duplicate ticket payload', 'Missing owner payload'],
    confidence: 'medium',
  },
};

export const INCIDENT_ALIAS_MAP: Record<string, string> = {
  endpoint_response: 'ransomware',
  ransomware_auto_containment: 'ransomware',
  phishing_campaign_response: 'phishing',
  suspicious_login_response: 'suspicious_login',
  waf: 'waf_attack',
  web_security: 'waf_attack',
  malicious_ip_response: 'malicious_ip',
  malware_hash_analysis: 'malware_hash',
  vulnerability_remediation_workflow: 'vulnerability',
  threat_intel_ioc_enrichment: 'threat_intel',
  ticket_automation_and_itsm_sync: 'ticket_automation',
};

export function getIncidentMapping(templateId?: string, generatorType?: string, name?: string): IncidentMitreMapping {
  const candidates = [templateId, generatorType, name?.toLowerCase().replace(/[^a-z0-9]+/g, '_')].filter(Boolean) as string[];
  for (const c of candidates) {
    if (INCIDENT_MITRE_MAPPINGS[c]) return INCIDENT_MITRE_MAPPINGS[c];
    if (INCIDENT_ALIAS_MAP[c] && INCIDENT_MITRE_MAPPINGS[INCIDENT_ALIAS_MAP[c]]) return INCIDENT_MITRE_MAPPINGS[INCIDENT_ALIAS_MAP[c]];
  }
  return INCIDENT_MITRE_MAPPINGS.threat_intel;
}
