// ============================================================
// SOARForge — Static MITRE Technique Registry (Phase 1)
// Local minimized knowledge base. Update checker comes later.
// ============================================================

import type { MitreTechniqueRecord } from './threat-knowledge-types';

export const THREAT_KNOWLEDGE_VERSION = {
  framework: 'MITRE ATT&CK Enterprise',
  localVersion: 'SOARForge-TK-1.0.0',
  sourceVersion: 'ATT&CK Enterprise reference snapshot',
  lastReviewed: '2026-05-17',
};

export const MITRE_TECHNIQUE_REGISTRY: Record<string, MitreTechniqueRecord> = {
  T1486: {
    techniqueId: 'T1486',
    name: 'Data Encrypted for Impact',
    description: 'Observed behavior where data is encrypted or made unavailable to disrupt business operations.',
    tactics: ['Impact'],
    platforms: ['Windows', 'Linux', 'macOS', 'Cloud'],
    dataSources: ['File Activity', 'Process Creation', 'Command Execution', 'EDR Telemetry'],
    isSubTechnique: false,
    defensiveFocus: ['File activity monitoring', 'Backup validation', 'Endpoint containment', 'Behavioral ransomware detection'],
    recommendedEntities: ['hostname', 'machine_id', 'username', 'file_path', 'file_hash', 'command_line'],
    recommendedDetections: ['ransomware_behavior', 'mass_file_rename', 'ransom_note_creation'],
    recommendedResponses: ['isolate_endpoint', 'collect_forensics', 'notify_soc', 'create_ticket'],
    falsePositiveNotes: ['Backup tools and encryption software can produce similar file activity patterns.'],
    version: '1.0',
    status: 'Approved_For_Production',
    customerLabel: 'Data Impact Behavior',
  },
  T1490: {
    techniqueId: 'T1490',
    name: 'Inhibit System Recovery',
    description: 'Observed behavior indicating attempts to reduce recovery capability or tamper with backup/recovery settings.',
    tactics: ['Impact'],
    platforms: ['Windows', 'Linux', 'Cloud'],
    dataSources: ['Command Execution', 'Process Creation', 'Windows Event Logs'],
    isSubTechnique: false,
    defensiveFocus: ['Recovery integrity monitoring', 'Shadow copy activity monitoring', 'Backup control protection'],
    recommendedEntities: ['hostname', 'username', 'command_line', 'process_name'],
    recommendedDetections: ['shadow_copy_deletion', 'recovery_config_change'],
    recommendedResponses: ['isolate_endpoint', 'validate_backups', 'create_ticket'],
    falsePositiveNotes: ['Backup maintenance jobs may legitimately run recovery commands.'],
    version: '1.0',
    status: 'Approved_For_Production',
    customerLabel: 'Recovery Control Alteration',
  },
  T1566: {
    techniqueId: 'T1566',
    name: 'Phishing',
    description: 'Observed email or messaging-based delivery behavior intended to influence user action.',
    tactics: ['Initial Access'],
    platforms: ['Office Suite', 'SaaS', 'Email Gateway'],
    dataSources: ['Email Gateway', 'Mail Message', 'URL Click Logs'],
    isSubTechnique: false,
    defensiveFocus: ['Email inspection', 'URL detonation', 'User reporting', 'Mailbox search'],
    recommendedEntities: ['sender_email', 'recipient_email', 'subject_line', 'url', 'message_id', 'attachment_hash'],
    recommendedDetections: ['phishing_link', 'malware_attachment', 'credential_harvest_url'],
    recommendedResponses: ['quarantine_email', 'block_sender', 'search_similar_emails', 'notify_recipients'],
    falsePositiveNotes: ['Marketing campaigns and partner mail may resemble suspicious bulk messages.'],
    version: '1.0',
    status: 'Approved_For_Production',
    customerLabel: 'Suspicious Message Delivery',
  },
  'T1566.001': {
    techniqueId: 'T1566.001',
    name: 'Spearphishing Attachment',
    description: 'Message delivery involving suspicious attachment artifacts.',
    tactics: ['Initial Access'],
    platforms: ['Office Suite', 'Email Gateway'],
    dataSources: ['Email Gateway', 'Attachment Metadata', 'Sandbox Verdict'],
    isSubTechnique: true,
    parentTechniqueId: 'T1566',
    defensiveFocus: ['Attachment detonation', 'Hash reputation', 'Mailbox remediation'],
    recommendedEntities: ['attachment_hash', 'sender_email', 'recipient_email', 'message_id'],
    recommendedDetections: ['malware_attachment'],
    recommendedResponses: ['quarantine_email', 'submit_file_to_sandbox', 'search_similar_emails'],
    falsePositiveNotes: ['Business documents and compressed attachments require reputation and sender context.'],
    version: '1.0',
    status: 'Approved_For_Production',
    customerLabel: 'Suspicious Attachment Delivery',
  },
  'T1566.002': {
    techniqueId: 'T1566.002',
    name: 'Spearphishing Link',
    description: 'Message delivery involving suspicious URLs or credential capture pages.',
    tactics: ['Initial Access'],
    platforms: ['Office Suite', 'Email Gateway', 'Browser'],
    dataSources: ['Email Gateway', 'URL Click Logs', 'Proxy Logs'],
    isSubTechnique: true,
    parentTechniqueId: 'T1566',
    defensiveFocus: ['URL reputation', 'Click tracking', 'Sender domain validation'],
    recommendedEntities: ['url', 'domain', 'sender_email', 'recipient_email', 'message_id'],
    recommendedDetections: ['phishing_link', 'credential_harvest_url'],
    recommendedResponses: ['quarantine_email', 'block_url', 'notify_recipients'],
    falsePositiveNotes: ['Legitimate URL shorteners and SaaS links should be verified before blocking.'],
    version: '1.0',
    status: 'Approved_For_Production',
    customerLabel: 'Suspicious Link Delivery',
  },
  T1204: {
    techniqueId: 'T1204',
    name: 'User Execution',
    description: 'Observed user interaction with a suspicious artifact, link, or attachment that requires awareness and response validation.',
    tactics: ['Execution'],
    platforms: ['Windows', 'macOS', 'Linux', 'Office Suite', 'Browser'],
    dataSources: ['Email Gateway', 'URL Click Logs', 'Endpoint Process Telemetry', 'Browser History'],
    isSubTechnique: false,
    defensiveFocus: ['User reporting', 'Attachment detonation', 'URL click tracking', 'Awareness validation'],
    recommendedEntities: ['recipient_email', 'url', 'attachment_hash', 'hostname', 'username'],
    recommendedDetections: ['user_clicked_suspicious_link', 'opened_suspicious_attachment'],
    recommendedResponses: ['notify_user', 'quarantine_email', 'create_ticket', 'review_endpoint_context'],
    falsePositiveNotes: ['Security awareness simulations and approved training campaigns may intentionally trigger similar telemetry.'],
    version: '1.0',
    status: 'Approved_For_Production',
    customerLabel: 'User Interaction Context',
  },
  T1078: {
    techniqueId: 'T1078',
    name: 'Valid Accounts',
    description: 'Observed use of valid credentials in a context that requires review.',
    tactics: ['Defense Evasion', 'Persistence', 'Privilege Escalation', 'Initial Access'],
    platforms: ['Windows', 'Linux', 'Cloud', 'SaaS'],
    dataSources: ['Authentication Logs', 'Identity Provider Logs', 'VPN Logs'],
    isSubTechnique: false,
    defensiveFocus: ['Login risk analysis', 'Session revocation', 'MFA enforcement'],
    recommendedEntities: ['username', 'upn', 'source_ip', 'geo', 'asn', 'mfa_status'],
    recommendedDetections: ['suspicious_login', 'impossible_travel', 'risky_user'],
    recommendedResponses: ['revoke_sessions', 'force_mfa_reset', 'create_ticket'],
    falsePositiveNotes: ['VPN, travel, and proxy use can produce unusual login geography.'],
    version: '1.0',
    status: 'Approved_For_Production',
    customerLabel: 'Unusual Account Usage',
  },
  'T1110.003': {
    techniqueId: 'T1110.003',
    name: 'Password Spraying',
    description: 'Observed authentication attempts across multiple accounts using common password patterns.',
    tactics: ['Credential Access'],
    platforms: ['Identity Provider', 'VPN', 'Windows', 'SaaS'],
    dataSources: ['Authentication Logs', 'Identity Provider Logs', 'VPN Logs'],
    isSubTechnique: true,
    parentTechniqueId: 'T1110',
    defensiveFocus: ['Authentication thresholding', 'Source IP reputation', 'Account lockout policy'],
    recommendedEntities: ['source_ip', 'username', 'user_count', 'failure_count'],
    recommendedDetections: ['password_spraying'],
    recommendedResponses: ['block_ip_with_context', 'force_password_reset', 'notify_soc'],
    falsePositiveNotes: ['Legacy sync jobs and misconfigured clients can generate repeated failures.'],
    version: '1.0',
    status: 'Approved_For_Production',
    customerLabel: 'Repeated Authentication Attempts',
  },
  T1190: {
    techniqueId: 'T1190',
    name: 'Exploit Public-Facing Application',
    description: 'Observed attempts against exposed web applications or APIs requiring validation and response.',
    tactics: ['Initial Access'],
    platforms: ['Web', 'Cloud', 'Network'],
    dataSources: ['WAF Logs', 'Web Server Logs', 'Application Logs', 'Network Traffic'],
    isSubTechnique: false,
    defensiveFocus: ['WAF rule validation', 'Virtual patching', 'Application telemetry', 'IP reputation'],
    recommendedEntities: ['client_ip', 'uri', 'method', 'status_code', 'waf_rule_id', 'owasp_category'],
    recommendedDetections: ['waf_attack', 'sqli_attempt', 'rce_attempt', 'web_shell_upload'],
    recommendedResponses: ['block_ip_with_context', 'create_ticket', 'notify_app_owner'],
    falsePositiveNotes: ['Internal scanners, health checks, and penetration tests must be allowlisted.'],
    version: '1.0',
    status: 'Approved_For_Production',
    customerLabel: 'Public Application Security Event',
  },
  T1003: {
    techniqueId: 'T1003',
    name: 'OS Credential Dumping',
    description: 'Observed credential access behavior requiring endpoint and identity investigation.',
    tactics: ['Credential Access'],
    platforms: ['Windows', 'Linux', 'macOS'],
    dataSources: ['Process Creation', 'EDR Telemetry', 'Security Logs'],
    isSubTechnique: false,
    defensiveFocus: ['LSASS access monitoring', 'Privilege use review', 'Endpoint containment'],
    recommendedEntities: ['hostname', 'username', 'process_name', 'process_id', 'command_line'],
    recommendedDetections: ['credential_dumping', 'lsass_access'],
    recommendedResponses: ['isolate_endpoint', 'reset_password', 'collect_forensics'],
    falsePositiveNotes: ['Security tools and backup utilities may access protected processes.'],
    version: '1.0',
    status: 'Approved_For_Production',
    customerLabel: 'Credential Access Behavior',
  },
  T1059: {
    techniqueId: 'T1059',
    name: 'Command and Scripting Interpreter',
    description: 'Observed script or shell execution requiring context review.',
    tactics: ['Execution'],
    platforms: ['Windows', 'Linux', 'macOS', 'Cloud'],
    dataSources: ['Process Creation', 'Command Execution', 'EDR Telemetry'],
    isSubTechnique: false,
    defensiveFocus: ['Command-line inspection', 'Parent-child process review', 'Script policy monitoring'],
    recommendedEntities: ['hostname', 'username', 'process_name', 'parent_process', 'command_line'],
    recommendedDetections: ['suspicious_powershell', 'suspicious_script_execution'],
    recommendedResponses: ['collect_process_tree', 'enrich_endpoint', 'create_ticket'],
    falsePositiveNotes: ['Administration, SCCM, Intune, and deployment tooling commonly execute scripts.'],
    version: '1.0',
    status: 'Approved_For_Production',
    customerLabel: 'Script Execution Behavior',
  },
  'T1059.001': {
    techniqueId: 'T1059.001',
    name: 'PowerShell',
    description: 'Observed PowerShell command execution requiring review of context and parent process.',
    tactics: ['Execution'],
    platforms: ['Windows'],
    dataSources: ['Process Creation', 'PowerShell Logs', 'EDR Telemetry'],
    isSubTechnique: true,
    parentTechniqueId: 'T1059',
    defensiveFocus: ['PowerShell logging', 'Encoded command detection', 'Admin tool allowlisting'],
    recommendedEntities: ['hostname', 'username', 'command_line', 'parent_process'],
    recommendedDetections: ['suspicious_powershell'],
    recommendedResponses: ['collect_process_tree', 'enrich_endpoint', 'create_ticket'],
    falsePositiveNotes: ['Legitimate remote administration and deployment scripts may match.'],
    version: '1.0',
    status: 'Approved_For_Production',
    customerLabel: 'PowerShell Execution Behavior',
  },
  'T1562.001': {
    techniqueId: 'T1562.001',
    name: 'Disable or Modify Tools',
    description: 'Observed security control modification or service tampering behavior.',
    tactics: ['Defense Evasion'],
    platforms: ['Windows', 'Linux', 'macOS', 'Cloud'],
    dataSources: ['Service Logs', 'EDR Telemetry', 'Process Creation'],
    isSubTechnique: true,
    parentTechniqueId: 'T1562',
    defensiveFocus: ['Sensor health monitoring', 'Service control monitoring', 'Tamper protection'],
    recommendedEntities: ['hostname', 'service_name', 'username', 'command_line'],
    recommendedDetections: ['edr_tampering'],
    recommendedResponses: ['notify_soc', 're_enable_sensor', 'isolate_endpoint_with_review'],
    falsePositiveNotes: ['Maintenance windows and agent upgrades can stop services legitimately.'],
    version: '1.0',
    status: 'Approved_For_Production',
    customerLabel: 'Security Control Alteration',
  },
  T1071: {
    techniqueId: 'T1071',
    name: 'Application Layer Protocol',
    description: 'Observed network communication pattern that may require command-and-control review.',
    tactics: ['Command and Control'],
    platforms: ['Network', 'Endpoint', 'Cloud'],
    dataSources: ['DNS Logs', 'Proxy Logs', 'Firewall Logs', 'NetFlow'],
    isSubTechnique: false,
    defensiveFocus: ['Beacon pattern analysis', 'Domain reputation', 'Proxy and DNS correlation'],
    recommendedEntities: ['source_ip', 'destination_ip', 'domain', 'url', 'hostname'],
    recommendedDetections: ['c2_beaconing', 'malicious_ip_communication'],
    recommendedResponses: ['block_ip_with_context', 'block_domain_with_context', 'create_ticket'],
    falsePositiveNotes: ['Telemetry, SaaS agents, and update services can generate periodic traffic.'],
    version: '1.0',
    status: 'Approved_For_Production',
    customerLabel: 'Unusual Network Communication',
  },
  T1048: {
    techniqueId: 'T1048',
    name: 'Exfiltration Over Alternative Protocol',
    description: 'Observed outbound transfer pattern requiring data movement review.',
    tactics: ['Exfiltration'],
    platforms: ['Network', 'Endpoint', 'Cloud'],
    dataSources: ['DLP Logs', 'Proxy Logs', 'Firewall Logs', 'Cloud Storage Logs'],
    isSubTechnique: false,
    defensiveFocus: ['Volume baseline monitoring', 'Destination reputation', 'Data classification review'],
    recommendedEntities: ['username', 'source_ip', 'destination_ip', 'domain', 'bytes_out'],
    recommendedDetections: ['data_exfiltration'],
    recommendedResponses: ['create_ticket', 'notify_data_owner', 'revoke_sessions_with_approval'],
    falsePositiveNotes: ['Approved business transfers and backups can exceed normal baselines.'],
    version: '1.0',
    status: 'Approved_For_Production',
    customerLabel: 'Unusual Data Transfer',
  },
  T1098: {
    techniqueId: 'T1098',
    name: 'Account Manipulation',
    description: 'Observed account or mailbox rule changes that require identity review.',
    tactics: ['Persistence', 'Privilege Escalation'],
    platforms: ['Windows', 'Cloud', 'SaaS', 'Office Suite'],
    dataSources: ['Identity Logs', 'Cloud Audit Logs', 'Mailbox Audit Logs'],
    isSubTechnique: false,
    defensiveFocus: ['Account change auditing', 'Mailbox rule monitoring', 'Privilege review'],
    recommendedEntities: ['username', 'email', 'rule_name', 'api_call', 'source_ip'],
    recommendedDetections: ['malicious_inbox_rule', 'cloud_iam_escalation'],
    recommendedResponses: ['remove_rule_with_review', 'revoke_sessions', 'create_ticket'],
    falsePositiveNotes: ['Helpdesk and automation processes may make legitimate account changes.'],
    version: '1.0',
    status: 'Approved_For_Production',
    customerLabel: 'Account Configuration Change',
  },
};

export function getTechnique(id: string): MitreTechniqueRecord | undefined {
  return MITRE_TECHNIQUE_REGISTRY[id];
}

export function getTechniques(ids: string[]): MitreTechniqueRecord[] {
  return ids.map((id) => MITRE_TECHNIQUE_REGISTRY[id]).filter((t): t is MitreTechniqueRecord => Boolean(t));
}
