import type { KnowledgeSourceDefinition } from './knowledge-update-types';

export const KNOWLEDGE_SOURCE_REGISTRY: KnowledgeSourceDefinition[] = [
  {
    id: 'mitre_attack_enterprise',
    name: 'MITRE ATT&CK Enterprise STIX',
    kind: 'mitre_attack',
    customerLabel: 'MITRE ATT&CK',
    purpose: 'Tactics, techniques, sub-techniques, mitigations, data sources, platforms, and relationships.',
    updateMode: 'hybrid',
    localVersion: '2026.05-local',
    officialUrl: 'https://attack.mitre.org/resources/attack-data-and-tools/',
    dataFormat: 'stix_21',
    authenticationRequired: false,
    recommendedFrequency: 'weekly',
    trustLevel: 'official',
    approvalRequired: true,
    supportsOfflineBundle: true,
    fieldsToExtract: ['id', 'type', 'name', 'description', 'external_references', 'x_mitre_platforms', 'x_mitre_deprecated', 'revoked', 'modified', 'created', 'kill_chain_phases'],
    parserStrategy: 'Normalize STIX attack-pattern, course-of-action, x-mitre-data-source, and relationship objects into local technique/data-source/countermeasure records.',
    diffStrategy: 'Compare object ID, modified timestamp, revoked/deprecated flags, external IDs, platforms, tactic phases, and relationships.',
    safetyNotes: ['Deprecated or revoked techniques must not delete local mappings automatically.', 'Affected templates are marked Review Recommended only.'],
    customerStatusWording: 'Official ATT&CK knowledge source. Updates require review before local datasets change.',
  },
  {
    id: 'mitre_d3fend',
    name: 'MITRE D3FEND',
    kind: 'mitre_d3fend',
    customerLabel: 'D3FEND Countermeasures',
    purpose: 'Defensive countermeasure and control mapping for response recommendations.',
    updateMode: 'offline_bundle',
    localVersion: '1.0-local',
    officialUrl: 'https://d3fend.mitre.org/resources/',
    dataFormat: 'json_ld',
    authenticationRequired: false,
    recommendedFrequency: 'monthly',
    trustLevel: 'official',
    approvalRequired: true,
    supportsOfflineBundle: true,
    fieldsToExtract: ['d3fend_id', 'label', 'definition', 'related_attack_technique', 'defensive_function'],
    parserStrategy: 'Store defensive metadata and ATT&CK relationships; never convert directly into destructive automation.',
    diffStrategy: 'Compare countermeasure IDs, labels, definitions, and ATT&CK mapping relationships.',
    safetyNotes: ['Use as defensive guidance only.', 'No destructive action generation from D3FEND updates.'],
    customerStatusWording: 'Defensive knowledge mapping. Updates enrich guidance after approval.',
  },
  {
    id: 'sigma_hq',
    name: 'SigmaHQ Rule Metadata',
    kind: 'sigma',
    customerLabel: 'Sigma Detection Logic',
    purpose: 'Detection reference metadata, logsource coverage, ATT&CK tags, false-positive hints, and severity levels.',
    updateMode: 'hybrid',
    localVersion: 'local-hints-1.0',
    officialUrl: 'https://sigmahq.io/docs/',
    dataFormat: 'yaml',
    authenticationRequired: false,
    recommendedFrequency: 'weekly',
    trustLevel: 'trusted_community',
    approvalRequired: true,
    supportsOfflineBundle: true,
    fieldsToExtract: ['id', 'title', 'status', 'description', 'logsource', 'tags', 'level', 'falsepositives', 'date', 'modified'],
    parserStrategy: 'Extract metadata and safe detection guidance only; do not copy full rule bodies into customer reports by default.',
    diffStrategy: 'Compare rule ID, title, status, modified date, level, logsource, ATT&CK tags, and false-positive metadata.',
    safetyNotes: ['Store metadata and detection hints.', 'SIEM-specific conversion must be validated by the customer.'],
    customerStatusWording: 'Detection metadata source. Updates may improve detection coverage recommendations.',
  },
  {
    id: 'cisa_kev',
    name: 'CISA Known Exploited Vulnerabilities',
    kind: 'cisa_kev',
    customerLabel: 'CISA KEV',
    purpose: 'Known exploited vulnerability awareness for vulnerability exposure and remediation-prioritization playbooks.',
    updateMode: 'hybrid',
    localVersion: 'source-ready',
    officialUrl: 'https://www.cisa.gov/known-exploited-vulnerabilities-catalog',
    dataFormat: 'json',
    authenticationRequired: false,
    recommendedFrequency: 'daily',
    trustLevel: 'official',
    approvalRequired: true,
    supportsOfflineBundle: true,
    fieldsToExtract: ['cveID', 'vendorProject', 'product', 'vulnerabilityName', 'dateAdded', 'dueDate', 'knownRansomwareCampaignUse', 'requiredAction'],
    parserStrategy: 'Normalize CVE, vendor, product, exploitation status, ransomware use, and due date into vulnerability knowledge records.',
    diffStrategy: 'Detect newly added CVEs and changed exploitation/ransomware/due-date metadata.',
    safetyNotes: ['Never auto-remediate production assets.', 'Mark vulnerability templates Review Recommended for analyst prioritization.'],
    customerStatusWording: 'Official exploited vulnerability source. Updates support prioritization and review.',
  },
  {
    id: 'lolbas',
    name: 'LOLBAS Metadata',
    kind: 'lolbas',
    customerLabel: 'LOLBAS',
    purpose: 'Living-off-the-land binary metadata and detection context for Windows abuse patterns.',
    updateMode: 'offline_bundle',
    localVersion: 'source-ready',
    officialUrl: 'https://lolbas-project.github.io/api/',
    dataFormat: 'yaml',
    authenticationRequired: false,
    recommendedFrequency: 'monthly',
    trustLevel: 'trusted_community',
    approvalRequired: true,
    supportsOfflineBundle: true,
    fieldsToExtract: ['name', 'path', 'description', 'commands', 'mitre_id', 'detection', 'resources'],
    parserStrategy: 'Extract binary names, categories, ATT&CK references, and defensive detection hints. Do not embed execution commands into playbooks.',
    diffStrategy: 'Compare binary name, ATT&CK mappings, detection references, and category changes.',
    safetyNotes: ['Use detection metadata only.', 'Do not include abuse commands in customer-facing generated playbooks.'],
    customerStatusWording: 'Living-off-the-land knowledge source. Updates improve detection and false-positive context.',
  },
  {
    id: 'atomic_red_team',
    name: 'Atomic Red Team Metadata',
    kind: 'atomic_tests',
    customerLabel: 'Atomic Test References',
    purpose: 'Safe validation reference metadata mapped to ATT&CK techniques and expected evidence.',
    updateMode: 'offline_bundle',
    localVersion: 'local-safe-tests-1.0',
    officialUrl: 'https://www.atomicredteam.io/',
    dataFormat: 'yaml',
    authenticationRequired: false,
    recommendedFrequency: 'monthly',
    trustLevel: 'trusted_community',
    approvalRequired: true,
    supportsOfflineBundle: true,
    fieldsToExtract: ['attack_technique', 'display_name', 'supported_platforms', 'executor', 'input_arguments', 'dependencies'],
    parserStrategy: 'Store metadata and expected evidence only. Unsafe or destructive commands are excluded from generated outputs.',
    diffStrategy: 'Compare technique IDs, platform coverage, display names, and validation references.',
    safetyNotes: ['No destructive commands.', 'Synthetic alert payloads are preferred for SOARForge validation.'],
    customerStatusWording: 'Validation knowledge source. Updates improve UAT planning after review.',
  },
  {
    id: 'platform_capability_matrix',
    name: 'SOAR Platform Capability Matrix',
    kind: 'platform_matrix',
    customerLabel: 'Platform Capability Matrix',
    purpose: 'SOAR platform limitations, direct-import confidence, connector requirements, and export constraints.',
    updateMode: 'local_only',
    localVersion: '1.0',
    dataFormat: 'json',
    authenticationRequired: false,
    recommendedFrequency: 'per_release',
    trustLevel: 'internal_curated',
    approvalRequired: true,
    supportsOfflineBundle: false,
    fieldsToExtract: ['platform_id', 'export_strategy', 'limitations', 'manual_requirements', 'confidence'],
    parserStrategy: 'Internal curated compatibility registry.',
    diffStrategy: 'Compare platform confidence, limitations, and manual requirements.',
    safetyNotes: ['Do not overstate runtime readiness without tenant validation.'],
    customerStatusWording: 'Internal platform readiness source used for export confidence.',
  },
];

export function getKnowledgeSourceDefinition(sourceId: string): KnowledgeSourceDefinition | undefined {
  return KNOWLEDGE_SOURCE_REGISTRY.find((source) => source.id === sourceId);
}
